"""removed map model

Revision ID: 9c0ca4ba34f0
Revises: b1c3685185a5
Create Date: 2020-10-15 18:49:18.219901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c0ca4ba34f0'
down_revision = 'b1c3685185a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maps')
    op.add_column('missings', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('missings', sa.Column('lng', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missings', 'lng')
    op.drop_column('missings', 'lat')
    op.create_table('maps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='maps_pkey')
    )
    # ### end Alembic commands ###
